"use client";

import { useState } from "react";
import {
  X,
  Download,
  ChevronDown,
  ChevronUp,
  MapPin,
  CalendarClock,
  Lock,
  Plus,
  CheckCircle2,
  XCircle,
  Users,
  Mail,
  Phone,
  UserRound,
  ShieldOff,
  MessageSquare,
} from "lucide-react";
import type { ChatLogEntry, Report, ReportStatus } from "@/lib/types";
import {
  STATUS_PIPELINE,
  allReportChatEntries,
  corroborations,
  reportChatSections,
} from "@/lib/types";
import { STATUS_META } from "@/lib/meta";
import { CategoryChip } from "@/components/Chips";
import { StatusPill } from "@/components/StatusPill";
import { SeverityBar } from "@/components/Severity";
import { addInternalNote, updateStatus } from "@/lib/store";
import { CITY } from "@/lib/seed";
import { cx, formatCoords, formatDateTime, timeAgo } from "@/lib/utils";

function buildDownloadText(report: Report): string {
  const loc =
    report.location.address ||
    report.location.crossStreet ||
    formatCoords(report.location.lat, report.location.lng);
  const lines = [
    `${CITY.name} — Municipal Service Request Record`,
    "=".repeat(60),
    "",
    `Report ID:     ${report.id}`,
    `Filed:         ${formatDateTime(report.createdAt)}`,
    `Noticed:       ${formatDateTime(report.noticedAt)}`,
    `Category:      ${report.category}`,
    `Status:        ${STATUS_META[report.status].label}`,
    `Severity:      ${report.severity}/10`,
    report.servicePriority ? `Priority:      ${report.servicePriority}` : null,
    "",
    report.formalTitle ? `Title: ${report.formalTitle}` : null,
    "",
    "OFFICIAL SUMMARY",
    "-".repeat(40),
    report.description,
    "",
    "LOCATION",
    "-".repeat(40),
    loc,
    `${formatCoords(report.location.lat, report.location.lng)} (${report.location.method})`,
    "",
    "CONTACT",
    "-".repeat(40),
    report.contact.anonymous
      ? "Anonymous submission"
      : [
          report.contact.name,
          report.contact.email,
          report.contact.phone,
        ]
          .filter(Boolean)
          .join("\n") || "No contact provided",
    "",
    report.media.length
      ? `Attachments: ${report.media.length} photo(s)/video(s)\n`
      : null,
    ...reportChatSections(report).flatMap((section) => [
      `INTAKE — ${section.label.toUpperCase()}`,
      "-".repeat(40),
      ...section.entries.map(
        (e) =>
          `[${formatDateTime(e.at)}] ${e.role === "user" ? "Resident" : "Beacon"}: ${e.text}`
      ),
      "",
    ]),
    `Generated by GovLink · ${formatDateTime(new Date().toISOString())}`,
  ];
  return lines.filter((l) => l !== null).join("\n");
}

function downloadReport(report: Report) {
  const text = buildDownloadText(report);
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${report.id}-service-request.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export function FormalReportModal({
  report,
  authorName,
  onClose,
  onShowOnMap,
}: {
  report: Report;
  authorName: string;
  onClose: () => void;
  onShowOnMap?: () => void;
}) {
  const [composer, setComposer] = useState<null | "resolved" | "declined">(null);
  const [noteText, setNoteText] = useState("");
  const [internalDraft, setInternalDraft] = useState("");
  const [chatOpen, setChatOpen] = useState(false);
  const [staffOpen, setStaffOpen] = useState(true);

  const rejected = !!report.resolution?.rejected;
  const count = corroborations(report);
  const chatSections = reportChatSections(report);
  const chatCount = allReportChatEntries(report).length;

  function setStatus(s: ReportStatus) {
    if (s === "resolved") {
      setComposer("resolved");
      return;
    }
    updateStatus(report.id, s);
  }

  function confirmResolution() {
    updateStatus(report.id, "resolved", {
      note: noteText.trim() || undefined,
      rejected: composer === "declined",
    });
    setComposer(null);
    setNoteText("");
  }

  function addNote(e: React.FormEvent) {
    e.preventDefault();
    if (!internalDraft.trim()) return;
    addInternalNote(report.id, internalDraft, authorName);
    setInternalDraft("");
  }

  const locLabel =
    report.location.address ||
    report.location.crossStreet ||
    formatCoords(report.location.lat, report.location.lng);

  return (
    <div
      className="fixed inset-0 z-[600] flex items-start justify-center overflow-y-auto bg-navy-950/50 p-4 sm:items-center sm:p-6"
      role="dialog"
      aria-modal="true"
      aria-label={`Service request ${report.id}`}
      onClick={onClose}
    >
      <div
        className="my-auto w-full max-w-3xl animate-fade-in"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="overflow-hidden rounded-xl border border-navy-200 bg-white shadow-2xl">
          {/* Toolbar */}
          <div className="flex items-center justify-between gap-3 border-b border-navy-100 bg-slate-50 px-4 py-3 sm:px-6">
            <p className="font-mono text-xs font-semibold text-ink-muted">
              {report.id}
            </p>
            <div className="flex items-center gap-2">
              {onShowOnMap && (
                <button
                  type="button"
                  onClick={onShowOnMap}
                  className="btn-outline !py-1.5 text-sm"
                >
                  <MapPin className="h-4 w-4" aria-hidden="true" />
                  Show on map
                </button>
              )}
              <button
                type="button"
                onClick={() => downloadReport(report)}
                className="btn-outline !py-1.5 text-sm"
              >
                <Download className="h-4 w-4" aria-hidden="true" />
                Download
              </button>
              <button
                type="button"
                onClick={onClose}
                className="btn-ghost !p-2"
                aria-label="Close report"
              >
                <X className="h-5 w-5" aria-hidden="true" />
              </button>
            </div>
          </div>

          {/* Formal document */}
          <div className="max-h-[70vh] overflow-y-auto">
            <article className="border-b-4 border-navy-900 px-6 py-8 sm:px-10 sm:py-10">
              <header className="border-b-2 border-navy-200 pb-6 text-center">
                <p className="text-xs font-bold uppercase tracking-[0.2em] text-navy-500">
                  City of {CITY.name}
                </p>
                <h2 className="mt-2 font-serif text-2xl font-bold text-navy-900 sm:text-3xl">
                  Municipal Service Request
                </h2>
                <p className="mt-1 text-sm text-ink-muted">
                  Official record · {formatDateTime(report.createdAt)}
                </p>
              </header>

              <div className="mt-6 flex flex-wrap items-center gap-2">
                <CategoryChip category={report.category} size="sm" />
                <StatusPill status={report.status} rejected={rejected} size="sm" />
                {report.servicePriority && (
                  <span className="chip bg-navy-100 px-2 py-0.5 text-[11px] font-semibold text-navy-800 ring-1 ring-navy-200">
                    {report.servicePriority}
                  </span>
                )}
                {count >= 2 && (
                  <span className="chip bg-accent-100 px-2 py-0.5 text-[11px] font-semibold text-accent-700">
                    <Users className="h-3 w-3" aria-hidden="true" />
                    {count} residents
                  </span>
                )}
              </div>

              {report.formalTitle && (
                <h3 className="mt-6 font-serif text-xl font-semibold leading-snug text-navy-900">
                  {report.formalTitle}
                </h3>
              )}

              <section className="mt-6">
                <h4 className="text-xs font-bold uppercase tracking-wider text-navy-500">
                  Official summary
                </h4>
                <p className="mt-2 font-serif text-base leading-relaxed text-ink">
                  {report.description}
                </p>
              </section>

              <div className="mt-6 rounded-lg bg-navy-50/70 p-4">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-semibold uppercase tracking-wide text-ink-muted">
                    Severity assessment
                  </span>
                  <span className="font-mono text-sm font-bold text-navy-900">
                    {report.severity}/10
                  </span>
                </div>
                <div className="mt-2">
                  <SeverityBar severity={report.severity} />
                </div>
              </div>

              {report.media.length > 0 && (
                <section className="mt-6">
                  <h4 className="text-xs font-bold uppercase tracking-wider text-navy-500">
                    Attachments
                  </h4>
                  <div className="mt-2 flex flex-wrap gap-2">
                    {report.media.map((m) => (
                      // eslint-disable-next-line @next/next/no-img-element
                      <img
                        key={m.id}
                        src={m.dataUrl}
                        alt={m.name || "Attachment"}
                        className="h-24 w-24 rounded-lg border border-navy-100 object-cover"
                      />
                    ))}
                  </div>
                </section>
              )}

              <dl className="mt-8 grid gap-4 border-t border-navy-100 pt-6 sm:grid-cols-2">
                <DocField icon={<MapPin className="h-4 w-4" />} label="Location">
                  {locLabel}
                  <span className="mt-0.5 block font-mono text-xs text-ink-muted">
                    {formatCoords(report.location.lat, report.location.lng)}
                  </span>
                </DocField>
                <DocField icon={<CalendarClock className="h-4 w-4" />} label="Noticed / reported">
                  {formatDateTime(report.noticedAt)}
                  <span className="mt-0.5 block text-xs text-ink-muted">
                    Filed {timeAgo(report.createdAt)}
                  </span>
                </DocField>
                <DocField
                  icon={
                    report.contact.anonymous ? (
                      <ShieldOff className="h-4 w-4" />
                    ) : (
                      <UserRound className="h-4 w-4" />
                    )
                  }
                  label="Contact"
                >
                  {report.contact.anonymous ? (
                    <span className="text-ink-muted">Anonymous submission</span>
                  ) : (
                    <div className="space-y-0.5">
                      {report.contact.name && <span>{report.contact.name}</span>}
                      {report.contact.email && (
                        <a
                          href={`mailto:${report.contact.email}`}
                          className="flex items-center gap-1.5 text-accent-700 hover:underline"
                        >
                          <Mail className="h-3.5 w-3.5" aria-hidden="true" />
                          {report.contact.email}
                        </a>
                      )}
                      {report.contact.phone && (
                        <a
                          href={`tel:${report.contact.phone}`}
                          className="flex items-center gap-1.5 text-accent-700 hover:underline"
                        >
                          <Phone className="h-3.5 w-3.5" aria-hidden="true" />
                          {report.contact.phone}
                        </a>
                      )}
                    </div>
                  )}
                </DocField>
              </dl>

              {/* Chat logs */}
              <section className="mt-8 border-t border-navy-100 pt-6">
                <button
                  type="button"
                  onClick={() => setChatOpen((o) => !o)}
                  className="flex w-full items-center justify-between gap-2 text-left"
                  aria-expanded={chatOpen}
                >
                  <span className="flex items-center gap-2 text-sm font-semibold text-navy-900">
                    <MessageSquare className="h-4 w-4 text-navy-500" aria-hidden="true" />
                    View chat logs
                    {chatCount > 0 && (
                      <span className="chip bg-navy-100 px-2 py-0.5 text-[11px] font-semibold text-navy-700">
                        {chatCount} messages
                      </span>
                    )}
                  </span>
                  {chatOpen ? (
                    <ChevronUp className="h-4 w-4 text-ink-muted" aria-hidden="true" />
                  ) : (
                    <ChevronDown className="h-4 w-4 text-ink-muted" aria-hidden="true" />
                  )}
                </button>
                {chatOpen && (
                  <div className="mt-4 space-y-4">
                    {chatSections.length === 0 ? (
                      <p className="text-sm text-ink-muted">
                        No intake conversation was recorded for this report.
                      </p>
                    ) : (
                      chatSections.map((section) => (
                        <div key={section.label}>
                          {chatSections.length > 1 && (
                            <h5 className="mb-2 text-xs font-bold uppercase tracking-wider text-navy-500">
                              {section.label}
                            </h5>
                          )}
                          <div className="space-y-3">
                            {section.entries.map((entry, i) => (
                              <ChatBubble key={`${section.label}-${entry.at}-${i}`} entry={entry} />
                            ))}
                          </div>
                        </div>
                      ))
                    )}
                  </div>
                )}
              </section>

              {count >= 2 && (
                <section className="mt-6 border-t border-navy-100 pt-6">
                  <h4 className="text-xs font-bold uppercase tracking-wider text-navy-500">
                    Corroborating submissions ({count})
                  </h4>
                  <ol className="mt-3 space-y-2">
                    {report.submissions.map((s, i) => (
                      <li
                        key={s.id}
                        className="rounded-lg border border-navy-100 bg-slate-50 p-3 text-sm"
                      >
                        <div className="flex items-center justify-between text-xs text-ink-muted">
                          <span className="font-medium text-navy-700">
                            {i === 0 ? "Original" : `Corroboration ${i}`}
                            {s.distanceM != null && ` · ${s.distanceM}m away`}
                          </span>
                          <span>{timeAgo(s.createdAt)}</span>
                        </div>
                        <p className="mt-1 text-ink">{s.description}</p>
                      </li>
                    ))}
                  </ol>
                </section>
              )}
            </article>

            {/* Staff workflow */}
            <div className="bg-slate-50 px-6 py-5 sm:px-10">
              <button
                type="button"
                onClick={() => setStaffOpen((o) => !o)}
                className="flex w-full items-center justify-between gap-2 text-left"
                aria-expanded={staffOpen}
              >
                <span className="text-xs font-bold uppercase tracking-wider text-navy-500">
                  Staff actions
                </span>
                {staffOpen ? (
                  <ChevronUp className="h-4 w-4 text-ink-muted" aria-hidden="true" />
                ) : (
                  <ChevronDown className="h-4 w-4 text-ink-muted" aria-hidden="true" />
                )}
              </button>

              {staffOpen && (
                <div className="mt-4 space-y-6">
                  <div>
                    <h4 className="text-xs font-semibold uppercase tracking-wide text-ink-muted">
                      Update status
                    </h4>
                    <div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">
                      {STATUS_PIPELINE.map((s) => {
                        const isCurrent = report.status === s;
                        return (
                          <button
                            key={s}
                            type="button"
                            onClick={() => setStatus(s)}
                            aria-pressed={isCurrent}
                            className={cx(
                              "rounded-lg px-3 py-2 text-sm font-semibold transition-colors",
                              isCurrent
                                ? "bg-navy-900 text-white"
                                : "border border-navy-200 bg-white text-navy-800 hover:border-navy-300 hover:bg-navy-50"
                            )}
                          >
                            {STATUS_META[s].label}
                          </button>
                        );
                      })}
                    </div>
                    <button
                      type="button"
                      onClick={() => {
                        setComposer("declined");
                        setNoteText("");
                      }}
                      className="btn-danger mt-2 w-full sm:w-auto"
                    >
                      <XCircle className="h-4 w-4" aria-hidden="true" />
                      Decline request
                    </button>

                    {composer && (
                      <div className="mt-3 rounded-xl border border-navy-200 bg-white p-4">
                        <h4 className="flex items-center gap-1.5 text-sm font-semibold text-navy-900">
                          {composer === "declined" ? (
                            <XCircle className="h-4 w-4 text-red-600" aria-hidden="true" />
                          ) : (
                            <CheckCircle2 className="h-4 w-4 text-emerald-600" aria-hidden="true" />
                          )}
                          {composer === "declined" ? "Decline this request" : "Resolve this issue"}
                        </h4>
                        <label htmlFor="resolution-note" className="mt-3 field-label">
                          Message to the resident{" "}
                          {composer === "declined" && (
                            <span className="font-normal text-red-600">(reason required)</span>
                          )}
                        </label>
                        <textarea
                          id="resolution-note"
                          rows={3}
                          className="field-input resize-none"
                          placeholder={
                            composer === "declined"
                              ? "Explain why this request can't be actioned…"
                              : "Describe what was done to fix it…"
                          }
                          value={noteText}
                          onChange={(e) => setNoteText(e.target.value)}
                        />
                        <div className="mt-3 flex gap-2">
                          <button
                            type="button"
                            onClick={confirmResolution}
                            disabled={composer === "declined" && !noteText.trim()}
                            className={cx(
                              "btn flex-1 text-white",
                              composer === "declined"
                                ? "bg-red-600 hover:bg-red-700"
                                : "bg-emerald-600 hover:bg-emerald-700"
                            )}
                          >
                            {composer === "declined" ? "Confirm decline" : "Confirm resolved"}
                          </button>
                          <button
                            type="button"
                            onClick={() => setComposer(null)}
                            className="btn-outline"
                          >
                            Cancel
                          </button>
                        </div>
                      </div>
                    )}
                  </div>

                  <div className="border-t border-navy-200 pt-5">
                    <h4 className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-ink-muted">
                      <Lock className="h-3.5 w-3.5" aria-hidden="true" />
                      Internal notes — staff only
                    </h4>
                    {report.internalNotes.length > 0 && (
                      <ol className="mt-3 space-y-2">
                        {report.internalNotes.map((n) => (
                          <li
                            key={n.id}
                            className="rounded-lg bg-amber-50/70 p-3 text-sm ring-1 ring-amber-100"
                          >
                            <p className="text-navy-900">{n.text}</p>
                            <p className="mt-1 text-xs text-ink-muted">
                              {n.author} · {timeAgo(n.createdAt)}
                            </p>
                          </li>
                        ))}
                      </ol>
                    )}
                    <form onSubmit={addNote} className="mt-3">
                      <label htmlFor="internal-note" className="sr-only">
                        Add an internal note
                      </label>
                      <textarea
                        id="internal-note"
                        rows={2}
                        className="field-input resize-none"
                        placeholder="Add a private note for your team…"
                        value={internalDraft}
                        onChange={(e) => setInternalDraft(e.target.value)}
                      />
                      <button
                        type="submit"
                        disabled={!internalDraft.trim()}
                        className="btn-outline mt-2 w-full sm:w-auto"
                      >
                        <Plus className="h-4 w-4" aria-hidden="true" />
                        Add internal note
                      </button>
                    </form>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function DocField({
  icon,
  label,
  children,
}: {
  icon: React.ReactNode;
  label: string;
  children: React.ReactNode;
}) {
  return (
    <div className="flex gap-3">
      <span className="mt-0.5 grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-navy-50 text-navy-500">
        {icon}
      </span>
      <div className="min-w-0">
        <dt className="text-xs font-semibold uppercase tracking-wide text-ink-muted">
          {label}
        </dt>
        <dd className="mt-0.5 text-sm text-navy-900">{children}</dd>
      </div>
    </div>
  );
}

function ChatBubble({ entry }: { entry: ChatLogEntry }) {
  const isUser = entry.role === "user";
  return (
    <div
      className={cx(
        "rounded-xl px-4 py-3 text-sm",
        isUser ? "ml-6 bg-navy-900 text-white" : "mr-6 bg-slate-100 text-ink"
      )}
    >
      <div className="mb-1 flex items-center justify-between gap-2 text-[11px] font-semibold uppercase tracking-wide opacity-70">
        <span>{isUser ? "Resident" : "Beacon"}</span>
        <time dateTime={entry.at}>{formatDateTime(entry.at)}</time>
      </div>
      <p className="leading-relaxed">{entry.text}</p>
    </div>
  );
}
